# Generated by Django 6.0.2 on 2026-06-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Actor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('imdb', models.FloatField()),
                ('genre', models.CharField(max_length=100)),
                ('actors', models.ManyToManyField(related_name='movies', to='Actor.actor')),
            ],
        ),
    ]
