# Generated by Django 6.0.2 on 2026-06-15 09:38

import Actor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.DateField(blank=True, null=True, validators=[Actor.models.validate_birthdate_limit])),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
